# -*- coding: utf-8 -*-
"""Production Operations Database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5SpM1x7pR8CrQ0CP7FF3fdOos09i0mf
"""

import sqlite3
import pandas as pd
import numpy as np

np.random.seed(42)

# Create sample data
num_rows = 1200

dates = pd.date_range(start="2023-01-01", periods=num_rows, freq="D")
oil_fields = ["Field A", "Field B", "Field C"]
regions = ["Offshore", "Onshore"]
well_ids = [f"WELL_{i}" for i in range(1, 21)]

data = {
    "date": np.random.choice(dates, num_rows),
    "oil_field": np.random.choice(oil_fields, num_rows),
    "well_id": np.random.choice(well_ids, num_rows),
    "region": np.random.choice(regions, num_rows),
    "production_barrels": np.random.randint(50, 500, num_rows),
    "operating_cost": np.random.randint(2000, 8000, num_rows)
}

df = pd.DataFrame(data)

# Buat SQLite database
conn = sqlite3.connect("oil_production.db")
df.to_sql("production", conn, if_exists="replace", index=False)

print("✓ Oil production database created")
df.head()

query1 = """
SELECT oil_field,
       SUM(production_barrels) AS total_production
FROM production
GROUP BY oil_field
ORDER BY total_production DESC;
"""
pd.read_sql_query(query1, conn)

query2 = """
SELECT well_id,
       ROUND(AVG(production_barrels), 2) AS avg_daily_production
FROM production
GROUP BY well_id
ORDER BY avg_daily_production DESC;
"""
pd.read_sql_query(query2, conn)

query3 = """
SELECT strftime('%Y-%m', date) AS month,
       SUM(production_barrels) AS total_production
FROM production
GROUP BY month
ORDER BY month;
"""
pd.read_sql_query(query3, conn)

query4 = """
SELECT region,
       SUM(production_barrels) AS total_production,
       ROUND(AVG(production_barrels), 2) AS avg_production
FROM production
GROUP BY region;
"""
pd.read_sql_query(query4, conn)

query5 = """
SELECT well_id,
       SUM(production_barrels) AS total_production
FROM production
GROUP BY well_id
ORDER BY total_production DESC
LIMIT 5;
"""
pd.read_sql_query(query5, conn)

conn.close()
print("Database connection closed")